# Generated by Django 3.2.18 on 2023-05-05 21:43

import backend.contact.models.user
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contact.user',),
            managers=[
                ('objects', backend.contact.models.user.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_canceled', models.BooleanField(default=False)),
                ('canceled_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('restored_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra', models.JSONField(blank=True, default=dict, null=True)),
                ('institution_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='مركز التحصيل الدراسي')),
                ('principals_subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='القسم العلمي')),
                ('degree', models.CharField(blank=True, choices=[('بدون شهادة', 'بدون شهادة'), ('ابتدائية', 'ابتدائية'), ('متوسطة', 'متوسطة'), ('إعدادية', 'إعدادية'), ('دبلوم', 'دبلوم'), ('دبلوم عالي', 'دبلوم عالي'), ('بكالوريوس', 'بكالوريوس'), ('ماجستير', 'ماجستير'), ('دكتوراه', 'دكتوراه')], max_length=255, null=True, verbose_name='الشهاده العلميه')),
                ('year', models.CharField(blank=True, max_length=255, null=True, verbose_name='سنه التخرج')),
                ('division', models.CharField(blank=True, max_length=255, null=True, verbose_name='الاختصاص العلمي')),
                ('canceled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_education_canceller', to=settings.AUTH_USER_MODEL)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_education_adder', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education', to='contact.employee')),
                ('restored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_education_restorer', to=settings.AUTH_USER_MODEL)),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='contact_education_updater', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
