# Generated by Django 3.2.18 on 2023-05-06 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20230506_0300'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMixin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, max_length=500)),
            ],
        ),
    ]
