# Generated by Django 3.2.18 on 2023-05-06 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_education_institution_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='institution_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='موقع المركز'),
        ),
    ]
