# Generated by Django 3.2.18 on 2023-05-06 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_auto_20230506_0415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='expected_graduation_date',
        ),
    ]
